### PR TITLE
Added binternet.ducks.party instance

### PR DESCRIPTION
**Pull request by nyuuzyou**

### CODE REVIEW

**Review by Ahwxorg — COMMENTED** [review]
Is it currently offline? lmao

**Comment by nyuuzyou** [comment]
> Is it currently offline? lmao

изображение
It works for me, also at https://uptime.ducks.party/status/ducks no problem

**Comment by Ahwxorg** [comment]
Then, it must not be in the Netherlands.

**Comment by codedipper** [comment]
> Then, it must not be in the Netherlands.

1. The instance works.
2. The ip on the domain is from a Russian VPS provider, located in Russia, but it could just be Wireguard.

**Comment by nyuuzyou** [comment]
> 2\. The ip on the domain is from a Russian VPS provider, located in Russia, but it could just be a reverse proxy.
>         Just add it?

You are right, the VPS is hosted by a Russian provider and in a Russian AS, However, the subnet and the server itself is geographically located in the Netherlands. For example, ipinfo.io correctly identifies the location. You can check ping with many services. For example https://perfops.net/ping-from-netherlands.
изображение

**Comment by Ahwxorg** [comment]
I have not added it yet because it seemed weird. This makes somewhat sense, however? I'll just add it.

**Pull request merged**
