### PR TITLE
add binternet.canine.tools

### PR DESCRIPTION
**Pull request by hyperdefined**

### CODE REVIEW

**Comment by Ahwxorg** [comment]
The IP address seems to locate to RoyaleHosting in The Netherlands, are you sure it's US-based?

**Comment by hyperdefined** [comment]
Yes, some IP databases show it in The Netherlands. RoyaleHosting is based there, and the server I rent is from US. Not sure if it was recycled or what, but it's in the US.

https://www.iplocation.net/

**Review by Ahwxorg — APPROVED** [review]
LGTM

**Comment by Ahwxorg** [comment]
Thank you for hosting Binternet <3

**Pull request merged**
