### PR TITLE
docker: `version` is deprecated, increment Alpine version

### PR DESCRIPTION
**Pull request by codedipper**

### CODE REVIEW

**Review by Ahwxorg — APPROVED** [review]
LGTM

**Comment by Ahwxorg** [comment]
Looks good, however, shouldn't we use alphine:stable, or whatever their latest tag is?

**Comment by codedipper** [comment]
> Looks good, however, shouldn't we use alphine:stable, or whatever their latest tag is?

You can so you don't have to update it manually, but it's better to have somebody look at it to make sure nothing breaks. Manually updating the tag also makes fresh prebuilt images to avoid an outdated "latest" Alpine version.

**Comment by Ahwxorg** [comment]
Agreed.

**Pull request merged**
