### PR TITLE
Update search.php

### PR DESCRIPTION
**Pull request by danii-saahir**
Fixes urlencode() receiving null as a parameter. Add check to ensure that $data is not null.

### CODE REVIEW

**Review by Ahwxorg — COMMENTED** [review]
Looks good, I'll read more in-depth and merge later.

**Comment by danii-saahir** [comment]
Thank you.

**Comment by Ahwxorg** [comment]
I'll look at this next week, life is a bit busy.

**Comment by danii-saahir** [comment]
Take your time boss, no pressure.

**Review by Ahwxorg — APPROVED** [review]
seems good!

**Pull request merged**
